# Lista de Exercício 3

## Questão 1
   - **1 - Crie os seguintes arquivos com extensão .py e implemente os métodos definidos para cada um deles:**
       - **stats.py**
           - Mean(X)
           - stdev(X)
           - var(y)
       - **metrics.py**
           - mse(y_true,y_pred)
           - rmse(y_true, y_pred)
           - mae(y_true, y_pred)
       - **linear_model.py**
           - classe SimpleLinearRegression
       - **resample.py**
           - split_train_test(n_elem, perc_train, seed)

## Questão 2

In [1]:
#Minha biblioteca
from mylibs import stats as st
from mylibs import metrics as mts
from mylibs import linear_model as lm
from mylibs import resample as rs

#Outras bibliotecas 
from sklearn import linear_model, metrics

### Item a
- a) Represente os dados a seguir:
    ![](../Exercicio_02/img/historical-housing-data.png)

In [2]:
X = st.np.array([[1400],[1600],[1700],[1875],[1100],[1550],[2350],[2450],[1425],[1700]])
y = st.np.array([245000,312000,279000,308000,199000,219000,405000,324000,319000,255000])

In [3]:
print('Lista X:\n {}'.format(X))
print('Lista Y:\n {}'.format(y))

Lista X:
 [[1400]
 [1600]
 [1700]
 [1875]
 [1100]
 [1550]
 [2350]
 [2450]
 [1425]
 [1700]]
Lista Y:
 [245000 312000 279000 308000 199000 219000 405000 324000 319000 255000]


### Item b
- b) Calcule média, desvio padrão e variância de X.

In [4]:
#My mean - X
print(st.mean(X))

1715.0


In [5]:
#Mean numpy - X
st.np.mean(X)

1715.0

In [6]:
#My var - X
print(st.var(X))

[157150.]


In [7]:
#Var numpy - X
st.np.var(X)

157150.0

In [8]:
#My standard deviation - X
print(st.stdev(X))

396.42149285829595


In [9]:
#Standard deviation numpy - X
st.np.std(X)

396.42149285829595

### Item c
- c) Divida os dados X, y para 70% de treino e 30% de teste. O resultado deve estar nas variáveis: X_train, y_train, X_test, y_test.
  - Dicas: 
    - **X_train = X[idx_train]**, onde idx_train é um array com os índices dos dados de treino.
    - **y_train = y[idx_train]**
    - **X_test = X[idx_test]**
    - **y_test = y[idx_test]**


### Manual

In [10]:
#Considerando para este caso as listas dos mesmo tamanho
#indiceElemTrain = st.math.floor(0.7 * len(X)) #Vai dividir a lista em 2, uma de 70% e uma de 30%

#Dividindo X
#X_train = X[:indiceElemTrain] #Nova lista que será usada p/ treinar o algoritmo, contendo 70% do valores da lista X
#X_test = X[indiceElemTrain:] ##Nova lista que será usada p/ testar o algoritmo, contendo 30% do valores da lista X

#Dividindo y
#y_train = y[:indiceElemTrain] #Nova lista que será usada p/ treinar o algoritmo, contendo 70% do valores da lista y
#y_test = y[indiceElemTrain:] #Nova lista que será usada p/ testar o algoritmo, contendo 30% do valores da lista y

### Usando modulo resample

In [11]:
idx_train,idx_test = rs.split_train_test(len(X), 0.7, 0)

In [12]:
#Dividindo X
X_train = X[idx_train]
X_test = X[idx_test]

#Dividindo y
y_train = y[idx_train]
y_test = y[idx_test]

In [13]:
print('Tamanho de X_train: {}'.format(len(X_train)))
print('Tamanho de X_test: {}'.format(len(X_test)))
print('Tamanho de y_train: {}'.format(len(y_train)))
print('Tamanho de y_test: {}'.format(len(y_test)))

Tamanho de X_train: 7
Tamanho de X_test: 3
Tamanho de y_train: 7
Tamanho de y_test: 3


In [14]:
print('X_train:\n\n {}'.format(X_train))
print('\nX_test:\n {}'.format(X_test))
print('\ny_train:\n {}'.format(y_train))
print('\ny_test:\n {}'.format(y_test))

X_train:

 [[1700]
 [1425]
 [1100]
 [1700]
 [1600]
 [2350]
 [2450]]

X_test:
 [[1875]
 [1400]
 [1550]]

y_train:
 [279000 319000 199000 255000 312000 405000 324000]

y_test:
 [308000 245000 219000]


### Item d
 - d) Crie um modelo de (1) **SimpleLinearRegression** (sua implementação) e outro modelo usando (2) **LinearRegression** do Scikit Learn.


In [15]:
#Meu modelo
meumodelo = lm.SimpleLinearRegression()

#Modelo Sklearn
dmodelo = linear_model.LinearRegression()

### Item e
 - e) Treine os modelos com os dados de treino (X_train, y_train).

In [16]:
meumodelo.fit(X_train,y_train)

In [17]:
dmodelo.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

### Item f
 - f) Faça as predições para os modelos usando os dados de teste (X_test).

In [18]:
import importlib
importlib.reload(st)
importlib.reload(mts)
importlib.reload(lm)
importlib.reload(rs);

In [19]:
y_pred1 = meumodelo.predict(X_test)
y_pred1

array([310458.49752129, 262834.11719842, 277873.39519512])

In [20]:
y_pred2 = dmodelo.predict(X_test)
y_pred2

array([310458.49752129, 262834.11719842, 277873.39519512])

## Item g
 - g) Calcule as métricas MSE, RMSE e MAE para avaliar os modelos criados comparando os rótulos dos dados de teste (y_test) com os dados preditos (y_pred).

In [21]:
#calculando erro usando y_pred1 -> meumodelo
print(mts.mse(y_test,y_pred1))
print(mts.rmse(y_test,y_pred1))
print(mts.mae(y_test,y_pred1))

1263392202.7033188
35544.22882414695
26388.66997161139


In [22]:
#calculando erro usando y_pred2 -> meumodelo
print(mts.mse(y_test,y_pred2))
print(mts.rmse(y_test,y_pred2))
print(mts.mae(y_test,y_pred2))

1263392202.703318
35544.228824146936
26388.66997161137


In [23]:
#calculando erro usando y_pred1 -> dmodelo -> sckit
print(metrics.mean_squared_error(y_test,y_pred1))
print(st.math.sqrt(metrics.mean_squared_error(y_test,y_pred1)))
print(metrics.mean_absolute_error(y_test,y_pred1))

1263392202.7033188
35544.22882414695
26388.66997161139


In [24]:
#calculando erro usando y_pred2 -> dmodelo -> sckit
print(metrics.mean_squared_error(y_test,y_pred2))
print(st.math.sqrt(metrics.mean_squared_error(y_test,y_pred2)))
print(metrics.mean_absolute_error(y_test,y_pred2))

1263392202.703318
35544.228824146936
26388.66997161137
