# Lista de exercícios 07

## Things default for Regression and Classification

In [1]:
import numpy as np
from mylibs import transform
from sklearn import preprocessing
from sklearn.model_selection import KFold
from sklearn import linear_model as lm
from sklearn import metrics
from sklearn import neighbors
from sklearn import naive_bayes
from sklearn.svm import SVC, SVR

### Datasets

In [2]:
from sklearn.datasets import load_boston, load_breast_cancer

# Regressão

## separando dados e label

In [3]:
#Separando os dados (X) do label (y)
X, y = load_boston(return_X_y=True)
#Aplicando K-fold para dividir os dados
kf = KFold(n_splits=5)

## Aplicando Standadization no dados

In [4]:
X = transform.standardization(X)

## Gradient Descent

In [5]:
erros_mse_gradient = np.empty((1,0))
erros_mae_gradient = np.empty((1,0))
gd = lm.SGDRegressor()

for train_index,test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    gd.fit(X_train.astype(float),y_train.astype(float))
    ŷ = gd.predict(X_test)
    erros_mse_gradient = np.append(erros_mse_gradient, np.sqrt(metrics.mean_squared_error(y_test, ŷ)))
    erros_mae_gradient = np.append(erros_mae_gradient, metrics.mean_absolute_error(y_test, ŷ))
    
erros_mse_gradient, erros_mae_gradient

/home/eudalio/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


(array([3.14148877, 6.11696982, 5.98849531, 8.92169933, 6.92419133]),
 array([2.24648653, 4.5474003 , 4.19496069, 5.29918198, 5.21488874]))

## Regressão Linear

In [6]:
erros_mse = np.empty((1,0))
erros_mae = np.empty((1,0))
modelo = lm.LinearRegression()

for train_index, test_index in kf.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]  
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_test)
    erros_mse = np.append(erros_mse, np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
    erros_mae = np.append(erros_mae, metrics.mean_absolute_error(y_test, y_pred))

erros_mse, erros_mae

(array([3.53279637, 5.10844425, 5.75499399, 8.99072043, 5.79520109]),
 array([2.62469524, 3.91244817, 4.38945068, 5.57366377, 4.78261237]))

## KNN

In [7]:
erros_mse_knn = np.empty((1,0))
erros_mae_knn = np.empty((1,0))
knn = neighbors.KNeighborsRegressor()

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index] 
    knn.fit(X_test, y_test)
    ŷ = knn.predict(X_test)
    erros_mse_knn = np.append(erros_mse_knn, np.sqrt(metrics.mean_squared_error(y_test, ŷ)))
    erros_mae_knn = np.append(erros_mae_knn, metrics.mean_absolute_error(y_test, ŷ))
erros_mse_knn, erros_mae_knn

(array([2.26624592, 3.47324712, 3.67532204, 5.00499196, 2.81528361]),
 array([1.59431373, 2.26019802, 2.57623762, 2.87306931, 2.01584158]))

## Naive bayes

In [8]:
erros_mse_nb = np.empty((1,0))
erros_mae_nb = np.empty((1,0))
nb = naive_bayes.GaussianNB()
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    nb.fit(X_test.astype(float), y_test.astype(int))
    ŷ = nb.predict(X_test.astype(float))
    erros_mse_nb = np.append(erros_mse_nb, np.sqrt(metrics.mean_squared_error(y_test, ŷ)))
    erros_mae_nb = np.append(erros_mae_nb, metrics.mean_absolute_error(y_test, ŷ))
    
erros_mse_nb, erros_mae_nb

(array([2.52980275, 5.07086416, 3.8979558 , 2.34085539, 3.99310049]),
 array([1.51470588, 2.22772277, 2.10693069, 1.46336634, 2.6009901 ]))

## SVM

In [9]:
erros_mse_svm = np.empty((1,0))
erros_mae_svm = np.empty((1,0))
svm = SVR()

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    svm.fit(X_train.astype(float), y_train.astype(int))
    ŷ = svm.predict(X_test.astype(float))
    erros_mse_svm = np.append(erros_mse_svm, np.sqrt(metrics.mean_squared_error(y_test, ŷ)))
    erros_mae_svm = np.append(erros_mae_svm, metrics.mean_absolute_error(y_test, ŷ))
erros_mse_svm, erros_mae_svm

(array([2.89634311, 6.85284779, 8.85535558, 7.57552989, 5.70077567]),
 array([2.09855906, 4.32743364, 6.14518067, 4.40433799, 4.31927614]))

# Classificação

In [10]:
XC, yc = load_breast_cancer(return_X_y=True)
XC = preprocessing.normalize(XC)
kf2 = KFold(n_splits=5)
kf2.get_n_splits(XC)

5

## Logistic Regression

In [11]:
# Metricas consideradas neste exercício
accuracy = np.empty((1,0))
precision = np.empty((1,0))
recall = np.empty((1,0))
f1_scr = np.empty((1,0))
aoc = np.empty((1,0))

# lr = LogisticRegression
lr = lm.LogisticRegression()

#Percorrendo as 5 splits de X
for train_index, test_index in kf2.split(XC):
    X_train, X_test = XC[train_index], XC[test_index]
    y_train, y_test = yc[train_index], yc[test_index]
    lr.fit(X_train, y_train)
    ŷ = lr.predict(X_test)
    accuracy = np.append(accuracy, metrics.accuracy_score(y_test, ŷ))
    precision = np.append(precision, metrics.precision_score(y_test, ŷ))
    recall = np.append(recall, metrics.recall_score(y_test, ŷ))
    f1_scr = np.append(f1_scr, metrics.f1_score(y_test, ŷ))
    aoc = np.append(aoc, metrics.roc_auc_score(y_test, ŷ))
    
    
print('Accuracy: {}'.format(np.mean(accuracy))),
print('Precision: {}'.format(np.mean(precision))),
print('Recall: {}'.format(np.mean(recall))),
print('F1-score: {}'.format(np.mean(f1_scr))),
print('AOC: {}'.format(np.mean(aoc)))

Accuracy: 0.7629715882626922
Precision: 0.725163627594447
Recall: 1.0
F1-score: 0.8314532638904447
AOC: 0.6994781652714137


## KNN

In [12]:
# Metricas consideradas neste exercício
accuracy = np.empty((1,0))
precision = np.empty((1,0))
recall = np.empty((1,0))
f1_scr = np.empty((1,0))
aoc = np.empty((1,0))

# knn2 = KnnClassifier
knn2 = neighbors.KNeighborsClassifier()

#Percorrendo as 5 splits de X
for train_index, test_index in kf2.split(XC):
    X_train, X_test = XC[train_index], XC[test_index]
    y_train, y_test = yc[train_index], yc[test_index]
    knn2.fit(X_train, y_train)
    ŷ = knn2.predict(X_test)
    accuracy = np.append(accuracy, metrics.accuracy_score(y_test, ŷ))
    precision = np.append(precision, metrics.precision_score(y_test, ŷ))
    recall = np.append(recall, metrics.recall_score(y_test, ŷ))
    f1_scr = np.append(f1_scr, metrics.f1_score(y_test, ŷ))
    aoc = np.append(aoc, metrics.roc_auc_score(y_test, ŷ))
    
    
print('Accuracy: {}'.format(np.mean(accuracy))),
print('Precision: {}'.format(np.mean(precision))),
print('Recall: {}'.format(np.mean(recall))),
print('F1-score: {}'.format(np.mean(f1_scr))),
print('AOC: {}'.format(np.mean(aoc)))

Accuracy: 0.912063344201211
Precision: 0.9045131069198961
Recall: 0.9517950979261499
F1-score: 0.9252891917988535
AOC: 0.903948002566267


## Naive Bayes

In [13]:
# Metricas consideradas neste exercício
accuracy = np.empty((1,0))
precision = np.empty((1,0))
recall = np.empty((1,0))
f1_scr = np.empty((1,0))
aoc = np.empty((1,0))

# nb2 = Naive Bayes
nb2 = naive_bayes.GaussianNB()

#Percorrendo as 5 splits de X
for train_index, test_index in kf2.split(XC):
    X_train, X_test = XC[train_index], XC[test_index]
    y_train, y_test = yc[train_index], yc[test_index]
    nb2.fit(X_train, y_train)
    ŷ = nb2.predict(X_test)
    accuracy = np.append(accuracy, metrics.accuracy_score(y_test, ŷ))
    precision = np.append(precision, metrics.precision_score(y_test, ŷ))
    recall = np.append(recall, metrics.recall_score(y_test, ŷ))
    f1_scr = np.append(f1_scr, metrics.f1_score(y_test, ŷ))
    aoc = np.append(aoc, metrics.roc_auc_score(y_test, ŷ))
    
    
print('Accuracy: {}'.format(np.mean(accuracy))),
print('Precision: {}'.format(np.mean(precision))),
print('Recall: {}'.format(np.mean(recall))),
print('F1-score: {}'.format(np.mean(f1_scr))),
print('AOC: {}'.format(np.mean(aoc)))

Accuracy: 0.8118770377270611
Precision: 0.9234334554334553
Recall: 0.7730618168963702
F1-score: 0.8374305020197077
AOC: 0.839484169328134


## SVM

In [14]:
# Metricas consideradas neste exercício
accuracy = np.empty((1,0))
precision = np.empty((1,0))
recall = np.empty((1,0))
f1_scr = np.empty((1,0))
aoc = np.empty((1,0))

# svm2 = SVM - Classificator
svm2 = SVC()

#Percorrendo as 5 splits de X
for train_index, test_index in kf2.split(XC):
    X_train, X_test = XC[train_index], XC[test_index]
    y_train, y_test = yc[train_index], yc[test_index]
    svm2.fit(X_train, y_train)
    ŷ = svm2.predict(X_test)
    accuracy = np.append(accuracy, metrics.accuracy_score(y_test, ŷ))
    precision = np.append(precision, metrics.precision_score(y_test, ŷ))
    recall = np.append(recall, metrics.recall_score(y_test, ŷ))
    f1_scr = np.append(f1_scr, metrics.f1_score(y_test, ŷ))
    aoc = np.append(aoc, metrics.roc_auc_score(y_test, ŷ))
    
    
print('Accuracy: {}'.format(np.mean(accuracy))),
print('Precision: {}'.format(np.mean(precision))),
print('Recall: {}'.format(np.mean(recall))),
print('F1-score: {}'.format(np.mean(f1_scr))),
print('AOC: {}'.format(np.mean(aoc)))

Accuracy: 0.6276665114112715
Precision: 0.6276665114112715
Recall: 1.0
F1-score: 0.7625524765154669
AOC: 0.5
