# Lista 05 - Aprendizado de Máquina

In [1]:
import numpy as np
from sklearn import metrics as skl_metr

In [2]:
from mylibs import metrics as my_metrics

In [3]:
y = ['cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat',  'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit'] 
y_pred = ['cat', 'cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'dog',  'cat', 'cat', 'dog', 'dog', 'dog', 'rabbit', 'dog', 'dog', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit']
cm = skl_metr.confusion_matrix(y, y_pred, labels=['cat', 'dog', 'rabbit']) 
print(cm)

[[ 5  3  0]
 [ 2  3  1]
 [ 0  2 11]]


In [4]:
skl_metr.accuracy_score(y,y_pred)

0.7037037037037037

In [5]:
my_metrics.accuracy(y,y_pred)

0.7037037037037037

In [6]:
skl_metr.precision_score(y,y_pred,average=None)[0]

0.7142857142857143

In [7]:
my_metrics.precision(y,y_pred)

0.7142857142857143

In [8]:
skl_metr.recall_score(y,y_pred,average=None)[0]

0.625

In [9]:
my_metrics.recall(y,y_pred)

0.625

In [12]:
skl_metr.f1_score(y,y_pred,average=None)[0]

0.6666666666666666

In [13]:
my_metrics.f1_measure(y,y_pred)

0.6666666666666666